[pytest]
testpaths = .
python_files = test_*.py
timeout = 3600
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integrity: marks tests that need dm-integrity
    io_uring: marks tests that need io_uring support
    reencrypt: marks tests that need re-encryption support (10G device)
addopts = -v --tb=short -ra
